"""Added stripes

Revision ID: be397a0d1d49
Revises: dc09d052bd72
Create Date: 2022-09-27 06:34:32.305442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be397a0d1d49'
down_revision = 'dc09d052bd72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_ranks', sa.Column('stripe_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_ranks', 'stripe_count')
    # ### end Alembic commands ###
