"""Added image path to users; Added created at and updated at in ranks

Revision ID: daad112148d1
Revises: 5ad89bfd6ba4
Create Date: 2022-10-01 18:08:57.946837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'daad112148d1'
down_revision = '5ad89bfd6ba4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_ranks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user_ranks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('user_ranks', 'rank_datetime')
    op.add_column('users', sa.Column('image_path', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_path')
    op.add_column('user_ranks', sa.Column('rank_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user_ranks', 'updated_at')
    op.drop_column('user_ranks', 'created_at')
    # ### end Alembic commands ###
